openapi: 3.0.1
info:
  title: Inditex Core Platform - API Price
  description: 'This API module access to price resource'
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: price
    description: 'Manage price source Controller'
paths:
  /price/by-filters:
    get:
      tags:
        - price
      summary: 'Get applicable price for a product and brand at a given date'
      description: 'This endpoint provides a way to get a Price'
      operationId: getPriceByFilter
      parameters:
        - in: query
          name: applicationDate
          required: true
          schema:
            type: string
            format: date-time
          example: "2020-06-14T10:00:00"
        - explode: true
          in: query
          name: productId
          required: true
          schema:
            type: integer
            format: int64
        - explode: true
          in: query
          name: brandId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
          description: Price found
        '404':
          $ref: '#/components/responses/PriceNotFound'

components:
  responses:
    PriceNotFound:
      description: Price not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    PriceResponse:
      type: object
      example:
        brandId: 6
        productId: 2
        currency: EUR
        priority: 1
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priority:
          type: integer
        priceDetail:
          $ref: '#/components/schemas/PriceDetailResponse'
        rangeDate:
          $ref: '#/components/schemas/RangeDateResponse'
    RateResponse:
      type: object
      example:
        code: STANDARD | PREMIUM | ...
        description: 'Premium Rate'
      properties:
        code:
          type: string
        description:
          type: string
    PriceDetailResponse:
      type: object
      example:
        currency: EUR
        finalPrice: 40.0
      properties:
        currency:
          enum:
            - EUR
            - USD
          example: EUR | USD
          type: string
        price:
          type: number
          format: decimal
        rate:
          $ref: '#/components/schemas/RateResponse'
    RangeDateResponse:
      type: object
      example:
        startDate: 2000-01-23T04:56:07.000+00:00
        endDate: 2000-01-23T04:56:07.000+00:00
      properties:
        startDate:
          format: date-time
          type: string
          example: "2020-06-14T10:00:00"
        endDate:
          format: date-time
          type: string
          example: "2020-06-14T10:00:00"
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        error:
          type: string
        message:
          type: string