version: '3.8'

services:
  app:
    build: .
    container_name: inditex-core-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Dspring.datasource.url=jdbc:h2:mem:testdb -Dh2.console.settings.web-allow-others=true